### ISSUE TITLE
openconnect doesn't go through VPN dns

### ISSUE THREAD

**Issue by itshaadi** [billz/raspap-webgui#150]
### Subject of the issue
i am using [openconnect VPN client](http://www.infradead.org/openconnect/) to bypass the internet filter. before using RaspAP everything worked fine. but now even though i can connect to the server successfully. it doesn't seems to completely bypass the internet (looks like traffic doesn't go through the VPN dns). also OpenVPN and Tor are very slow in iran so openconnect is my only option 😞 

### Your environment
* Raspberry Pi 3 Model B
* Raspbian Stretch
* RaspAP Quick Install
* Other software or services running with RaspAP?
 Pi-hole, but i did tried RaspAP without Pi-hole the problem is within the configuration of RaspAP

### Steps to reproduce
optional: living in a restricted country preferably iran
install openconnect `sudo apt install openconnect`
connect to a server `sudo openconnect server ip`

### Expected behaviour
bypas the internet filter.

### Actual behaviour
looks like traffic doesn't go through the VPN dns.

**Comment by billz** [comment]
Check your original settings in `dnsmasq.conf`. This file is backed up to `/etc/raspap/backups` by the Quick Installer. The issue is projects like OpenConnect, Pi-hole and RaspAP all manage DNS in one way or another. See also [this FAQ ](https://github.com/billz/raspap-webgui/wiki/FAQs#pihole) related to Pi-hole integration and dnsmasq which may also apply.
