### ISSUE TITLE
Tested on Stretch and RasPi 3B+?

### ISSUE THREAD

**Issue by glynhudson** [billz/raspap-webgui#202]
Has anyone been able to successfully run this on a RasPi 3B+ running Stretch?

**Comment by BI7PRK** [comment]
yes, i can run on pi3b+  kali OS. but it can't authenticate.  I have tried all the encryptions.

**Comment by glynhudson** [comment]
What do you mean by can't authenticate? I've just tried running on RasPi 3B+ (default Raspbian Stretch). It seems to startup ok, however, hotspot doesnt seem to work and it doesn't seem to be able to scan for client networks. Anyone else tried using this with Stretch? Any additional steps required?

**Comment by ginodouglas** [comment]
I had the same problem with pi3b+ and Stretch, putting the SD card in a pi3b it worked fine.

**Comment by billz** [comment]
Did you set up everything in raspi-config? The WiFi country setting is important. 

Per the Raspbian [release notes](http://downloads.raspberrypi.org/raspbian/release_notes.txt), WiFi is disabled until the wireless regulatory domain is set (Pi 3 B+ only). There is no default value. The quick installer doesn't handle this step for you.

Be sure to shutdown and boot (not reboot) your Pi  after changing this setting.

If you have trouble getting the hostapd service to start, add the following to `/etc/rc.local` just before `exit 0`:

```
service hostapd stop
sleep 5
service hostapd start
```

**Comment by danielwilson654** [comment]
I have the same issue on a clean install of ubuntu 18.04 on arm. 
```
Attempting to start hotspotx
HostAPD is not running
```
Here is the output of systemctl status hostapd

`● hostapd.service - LSB: Advanced IEEE 802.11 management daemon
   Loaded: loaded (/etc/init.d/hostapd; generated)
   Active: active (exited) since Mon 2018-11-12 03:42:44 UTC; 10min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1395 ExecStop=/etc/init.d/hostapd stop (code=exited, status=0/SUCCESS)
  Process: 1416 ExecStart=/etc/init.d/hostapd start (code=exited, status=0/SUCCESS)

Nov 12 03:42:44 nanopiair systemd[1]: Starting LSB: Advanced IEEE 802.11 management daemon...
Nov 12 03:42:44 nanopiair systemd[1]: Started LSB: Advanced IEEE 802.11 management daemon.
`

**Comment by danielwilson654** [comment]
This might be the case as ubuntu doesn’t use a wpa_supplicant.conf file. On ubuntu, wpa_supplicant it is managed dynamically somehow.

**Comment by billz** [comment]
>  On ubuntu, wpa_supplicant it is managed dynamically somehow. 

For better or worse, Ubuntu 18.04 now uses `netplan` to configure networking. As RaspAP is designed for Raspbian, this setup is not supported.

**Comment by billz** [comment]
Please refer to https://github.com/billz/raspap-webgui/issues/287#issuecomment-469083944

Closing this issue. Reopen if needed, thanks.
