### ISSUE TITLE
redirecting connected devices certain urls to local webserver

### ISSUE THREAD

**Issue by lujunq** [billz/raspap-webgui#215]
With the hotspot correcly configured and running, it would be nice to have some redirection rules for connected devices, like blocking some urls or even redirecting them to some local addresses, like myapp.com => 127.0.0.1/myapp, since lighttpd and php is installed on the Raspap configuration process. This would make Raspap great for providing services for connected iot devices... 

Can this be add to the configuration interface?

**Comment by glaszig** [comment]
please correct me, but this would need:

1. ui to define redirects in the form `trigger domain => target url`, e.g., `google.com => example.com/google`.
2. have dhcpd configure clients with the raspap itself as dns
3. configure dnsmasq to hijack domains configured as redirect triggers and resolve to the raspap's address itself
4. configure lighttpd to listen for the trigger domains, lookup the the target url, and issue a redirect response

i see a problem with point 3 because the raspap is potentially running on multiple interfaces so the question becomes to wich of those address does dnsmasq resolve...
