### ISSUE TITLE
Cannot scan for networks "Undefined variable: networks"

### ISSUE THREAD

**Issue by glynhudson** [billz/raspap-webgui#221]
### Subject of the issue
The GUI is not able to scan for networosk 

### Your environment
* Raspberry Pi hardware: 3B+
* Raspbian version: Stretch
* RaspAP Quick Install or Manual setup?: Manual 
* Other software or services running with RaspAP?: Moved lighttpd port 81 since apache is running Emoncms on port 80

### Steps to reproduce
Install and run 

### Expected behaviour
Local WiFi networks should be displayed

### Actual behaviour

![selection_283](https://user-images.githubusercontent.com/758844/43793197-c3816e82-9a72-11e8-98f6-c1a78c5fcfff.png)

```
$ sudo  tail  /var/log/lighttpd/error.log
2018-08-07 17:48:27: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Notice:  Undefined variable: networks in /var/www/html/includes/configure_client.php on line 183
2018-08-07 17:48:27: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/includes/configure_client.php on line 183
```

**Comment by mlekorlz** [comment]
I have the same problem with Pi Zero W

**Comment by D9ping** [comment]
Could you run on a terminal:
``
sudo wpa_cli -i wlan0 scan
``
and then run:
``
sudo wpa_cli -i wlan0 scan_results
``

And tell me if you then see a list of wi-fi networks on the terminal.

**Comment by PRO2XY** [comment]
@D9ping @glynhudson : Please see [my reply on issue 245](https://github.com/billz/raspap-webgui/issues/245#issuecomment-435588181).
This is due to incomplete entry on `/etc/sudoers` for `wpa_cli` it needs the interface to be defined in sudoers file, or the entire `wpa_cli` exposed.
Another problem is the wrongly defined variable `$scanned_networks` which needs to be `$networks`.

Please correct me if I am wrong.

**Comment by billz** [comment]
Resolved with https://github.com/billz/raspap-webgui/commit/d912eb5a1272d769bbe1fbfd365af7ae0228e215.
